### ISSUE TITLE
Add seperate settings for the Nether and the End

### ISSUE THREAD

**Issue by Setadokalo** [Setadokalo/custom-fog#1]

**Comment by Setadokalo** [comment]
This has partially been implemented now using the dimensional black/whitelist, but I'd still like to look into per-dimension settings.

**Comment by Jarfeh** [comment]
How would I use the black/whitelist? I've attempted putting multiple dimensions in the brackets, and nothing changed

**Comment by Setadokalo** [comment]
huh, I think that should work; I'll check myself when I have the chance - the holidays kinda wreck my free time.

**Comment by Setadokalo** [comment]
just tested it myself with 
```
listMode = "BLACKLIST"
dimensionsList = ["minecraft:the_end", "minecraft:the_nether"]
```
and it works fine; are you using 1.2.0?
