### ISSUE TITLE
Rendering Issue Under Lava with Sodium

### ISSUE THREAD

**Issue by Snowiez** [Setadokalo/custom-fog#18]
![2021-03-08_11 17 59](https://user-images.githubusercontent.com/10224646/110315034-926e7580-8000-11eb-9aca-92fcd1c69507.png)

Lots of blocks not rendering when under lava. It should be easy to see when moving around.

Only seems to happen with Sodium.

**Comment by Felix14-v2** [comment]
> Only seems to happen with Sodium
You should disable fog occlusion in the Sodium video settings.

**Comment by Setadokalo** [comment]
as felix said, this has to do with how sodium tries to avoid rendering chunks that are hidden by fog; there's not much I can do about it without some invasive mixins. Best way to avoid this is to disable fog occlusion entirely.
