### ISSUE TITLE
[1.17] Fog settings apply underwater 

### ISSUE THREAD

**Issue by b3spectacled** [Setadokalo/custom-fog#21]
Fog settings appear to also apply to underwater fog. Image examples:

Settings:
* Fog start: 25%
* Fog end: 100%

With Custom Fog, above water:
![Above water](https://i.imgur.com/H4dN87m.png)

With Custom Fog, underwater:
![Underwater](https://i.imgur.com/QIGNyy3.png)

Vanilla, underwater:
![Underwater, vanilla](https://i.imgur.com/0yTUpSX.png)

**Comment by Setadokalo** [comment]
v2.0 now has a separate config for underwater fog. Thanks for the report!
