### ISSUE TITLE
Server components

### ISSUE THREAD

**Issue by Madis0** [Setadokalo/custom-fog#22]
Why does this mod have server-side components? Every server can already set the render distance, so how can a modified fog setting give any advantage?

**Comment by VoidLock92** [comment]
Allowing to force the fog level can have many uses. You can use it in some worlds you want to have no fog or very thick fog. If you run a PvP server like me you can use it to force all clients on the same fog level so there is no advantage for anyone who manipulates client files to change the distance. Maybe you want to make a maze world of some sort or a hardcore parkcore map and want intense fog to limit view without seeing the edge of the chunks. IMO one of the most ugly things is seeing un-rendered chunks, so I personally use it on my servers so the fog is so intense right around chunk ends that you cannot see the chunks populate or missing. Get creative :) also if you don't need that feature why not just not use it? The more features the better IMO. That does not mean you NEED to use them all. If you don't want that feature simply don't install the mod on a server.

**Comment by Madis0** [comment]
Well, if you enforce a render distance already, there can't be any advantage via the fog. 

What I'm concerned about is player annoyance and inconsistency - a player who doesn't like the fog could suddenly be forced to see it and a player who prefers a thick fog could suffenly see the "border" instead. In other words, the mod will stop doing what it is supposed to.
