### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by bestsoft100** [Setadokalo/custom-fog#23]
I think it should be possible to set linear fog end to more than 100% so there are no chunks completely occluded by fog.
It is possible to do that by editing the config file, but the GUI doesn't allow it.

Also I think there should be an option to disable fog entirely.

Linear Fog End 100%:
![2021-08-05_22 54 12](https://user-images.githubusercontent.com/49400900/128419891-37ea9d49-d6c9-4cda-8975-9c13fa8e2d41.png)

Linear Fog End 200%:
Looks better than no fog, but you can still see everything
![2021-08-05_22 53 59](https://user-images.githubusercontent.com/49400900/128419896-fdfa8c7f-f8c9-4465-93f2-5c9f6110ded5.png)

**Comment by Setadokalo** [comment]
Both of these are now possible - in v2.0 you can click on a slider to set it's value directly, with no range restriction, and the slider will adjust it's range to match, and the fog mode button from 1.16 has returned.
