### ISSUE TITLE
incompatibility with Better Sodium Video Settings Button

### ISSUE THREAD

**Issue by MiFliK** [Setadokalo/custom-fog#25]
nstalling Better Sodium Video Settings Button Mod
Together with the custom fog
Causes the game to crash
other mods were not installed at that time
except sodium sodium extra custom fog Better Sodium Video Settings Button
There seems to be no problem with the first three mods.

**Comment by Setadokalo** [comment]
I have a solution for this ready to go, but I'll need some collaboration from the BSVSB creator to release it.
Thanks for the report!

**Comment by Setadokalo** [comment]
I believe this has been resolved. If it's not, please reopen
