### ISSUE TITLE
Visual bugs

### ISSUE THREAD

**Issue by LiLPNuTTy** [Setadokalo/custom-fog#27]
I have no clue what causes this (no other mods except fabric api installed) When sodium is installed this only affects mobs and particles.
![image](https://user-images.githubusercontent.com/73256738/140722583-3cfb2aad-0d83-4830-9854-75cb8b5bfad6.png)
heres the same place with exponential fog turned off (the same bug is present in exponential ^2) 
![image](https://user-images.githubusercontent.com/73256738/140722644-67147498-7d88-4b99-b1ab-086746a1d17c.png)

**Comment by Xrey274** [comment]
Yep exponential and exponential^2 are both completely broken. Should be removed imo.

**Comment by Setadokalo** [comment]
Exponential and Exponential^2 fog modes require you to disable fog occlusion in the sodium settings menu, as is mentioned on this mod's curseforge page.
