### ISSUE TITLE
Game Crash 1.18.2 - "Critical injection failure"

### ISSUE THREAD

**Issue by SepiaPages** [Setadokalo/custom-fog#32]
I don't quite know why it would crash updating from 1.18.1 to 1.18.2 because there wasn't a huge amount of changes between the two versions, but here we are. 

This mod makes a huge difference in enjoying Minecraft! I really hope this continues to be worked on. :) 

I've attached the crash log. Here's a key part of it:
`Critical injection failure: Callback method setFogFalloff(Lnet/minecraft/class_4184;Lnet/minecraft/class_758$class_4596;FZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_5636;Lnet/minecraft/class_1297;)V in custom-fog.mixins.json:RendererMixin from mod custom-fog failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap custom-fog-refmap.json`

[crash-2022-03-06_13.06.36-client.txt](https://github.com/Setadokalo/custom-fog/files/8193233/crash-2022-03-06_13.06.36-client.txt)

**Comment by JosefLitos** [comment]
Please fix this for 1.18.2.
The game looks so weird without this mod.

**Comment by StereoMadnessss** [comment]
I can't survive with my Beta setup without this

**Comment by JosefLitos** [comment]
I believe there is a working 1.18.2 version available on their Discord server.
No idea why it hasn't been uploaded to Github yet.

**Comment by StereoMadnessss** [comment]
Here is the download for the jar but Seta said he wasn't satisfied with it so be careful.
[https://cdn.discordapp.com/attachments/767238841429786630/953012302528016444/custom-fog-2.1.0-1.18.2.jar](https://cdn.discordapp.com/attachments/767238841429786630/953012302528016444/custom-fog-2.1.0-1.18.2.jar)
