### ISSUE TITLE
Crashes on Launch 

### ISSUE THREAD

**Issue by ThePolishHussar** [Setadokalo/custom-fog#4]
Mods i have installed:
Fabric Capes
Fabric API
Kotlin
lamb dynamic lights
lithium
mod menu
ok zoomer
phosphor
raised clouds
sodium

MC Crash Report : 
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 10/20/20 11:05 AM
Description: Unexpected error

java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    net/minecraft/class_758.method_3211(Lnet/minecraft/class_4184;Lnet/minecraft/class_758$class_4596;FZ)V @309: fload
  Reason:
    Type top (current frame, locals[7]) is not assignable to float
  Current Frame:
    bci: @309
    flags: { }
    locals: { 'net/minecraft/class_4184', 'net/minecraft/class_758$class_4596', float, integer, 'net/minecraft/class_3610', 'net/minecraft/class_1297', float }
    stack: { }
  Bytecode:
    0x0000000: 2ab6 003c 3a04 2ab6 0108 3a05 1904 b200
    0x0000010: 42b6 0048 9900 5e0c 3806 1301 5438 0619
    0x0000020: 05c1 0121 9900 4019 05c0 0121 3a07 1706
    0x0000030: 1907 b601 2519 07b6 0125 6a13 0155 6a66
    0x0000040: 3806 1907 b401 5919 07b6 015c b601 5f3a
    0x0000050: 0819 08b6 0163 b201 67a6 000b 1706 1301
    0x0000060: 6862 3806 1706 b801 49b2 014d b801 51a7
    0x0000070: 00ff 1904 b200 7eb6 0048 9900 2e19 05c1
    0x0000080: 010a 9900 1c19 05c0 010a b201 6bb6 0114
    0x0000090: 9900 0e0b 3806 1301 6c38 07a7 00a8 1283
    0x00000a0: 3806 0c38 07a7 009e 1905 c101 0a99 0058
    0x00000b0: 1905 c001 0ab2 0110 b601 1499 004a 1905
    0x00000c0: c001 0ab2 0110 b601 18b6 011d 3608 0c15
    0x00000d0: 0886 1301 1e6e b801 2924 1301 6db8 0070
    0x00000e0: 3809 2bb2 0171 a600 110b 3806 1709 1301
    0x00000f0: 726a 3807 a700 0e17 0912 836a 3806 1709
    0x0000100: 3807 a700 411d 9900 1924 1301 546a 3806
    0x0000110: 2413 0173 b801 2912 aa6a 3807 a700 272b
    0x0000120: b201 71a6 000c 0b38 0624 3807 a700 1724
    0x0000130: 1284 6a38 0617 072a 2b24 1db8 0177 3807
    0x0000140: 2438 0717 06b8 017a 1707 b801 7db2 0180
    0x0000150: b801 512a 2b24 1dbb 0182 5913 0183 03b7
    0x0000160: 0186 1904 1905 1706 b801 8ab8 018d b1  
  Stackmap Table:
    append_frame(@100,Object[#68],Object[#402],Float)
    chop_frame(@114,1)
    same_frame(@158)
    same_frame(@168)
    full_frame(@247,{Object[#56],Object[#12],Float,Integer,Object[#68],Object[#402],Top,Top,Integer,Float},{})
    full_frame(@258,{Object[#56],Object[#12],Float,Integer,Object[#68],Object[#402],Float,Float,Integer,Float},{})
    full_frame(@261,{Object[#56],Object[#12],Float,Integer,Object[#68],Object[#402]},{})
    same_frame(@287)
    same_frame(@303)
    append_frame(@323,Float,Float)
    chop_frame(@366,1)

	at net.minecraft.class_310.method_1523(class_310.java:1014)
	at net.minecraft.class_310.method_1514(class_310.java:656)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:227)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1284359120 bytes (1224 MB) / 2684354560 bytes (2560 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		autoconfig1u: Auto Config v1 Updated 3.2.2
		capes: Capes 1.1.0
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.8.1
		custom-fog: Custom Fog 0.0.1
		fabric: Fabric API 0.24.1+build.412-1.16
		fabric-api-base: Fabric API Base 0.2.0+9f0fb4b895
		fabric-biome-api-v1: Fabric Biome API (v1) 2.0.0+c29459ab95
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8995
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339895
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083695
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f95
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86695
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d95
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+f8ac1db295
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.2+f8ac1db295
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+f8ac1db295
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963695
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c695
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c595
		fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea18895
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
		fabric-models-v0: Fabric Models (v0) 0.1.1+f8ac1db295
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b95
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f95
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.0+c270b09895
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.0+432ea18895
		fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e95
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.6.0+9f0fb4b895
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.2+2b46237995
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.2+2b46237995
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+f8ac1db295
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+f8ac1db295
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+f8ac1db295
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+f8ac1db295
		fabric-rendering-v1: Fabric Rendering (v1) 1.3.1+f8ac1db295
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf95
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+8724984195
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db295
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c5995
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb895
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.4+2b46237995
		fabricloader: Fabric Loader 0.10.1+build.209
		fiber: fiber 0.23.0-2
		lambdynlights: LambDynamicLights 1.3.1+1.16.3
		lithium: Lithium 0.5.6
		minecraft: Minecraft 1.16.3
		modmenu: Mod Menu 1.14.6+build.31
		okzoomer: Ok Zoomer 4.0.1+1.16.2
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
		phosphor: Phosphor 0.6.0+build.7
		raisedclouds: Raised Clouds 1.0.0
		sodium: Sodium 0.1.0
		spruceui: SpruceUI 1.6.4
	Launched Version: fabric-loader-0.10.1+build.209-1.16.3
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce RTX 2060 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.38, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric/autoconfig1u, fabric/cloth-config2, fabric/fabric, fabric/fabric-api-base, fabric/fabric-biome-api-v1, fabric/fabric-blockrenderlayer-v1, fabric/fabric-containers-v0, fabric/fabric-content-registries-v0, fabric/fabric-crash-report-info-v1, fabric/fabric-events-interaction-v0, fabric/fabric-events-lifecycle-v0, fabric/fabric-game-rule-api-v1, fabric/fabric-item-api-v1, fabric/fabric-item-groups-v0, fabric/fabric-key-binding-api-v1, fabric/fabric-keybindings-v0, fabric/fabric-language-kotlin, fabric/fabric-lifecycle-events-v1, fabric/fabric-loot-tables-v1, fabric/fabric-mining-levels-v0, fabric/fabric-models-v0, fabric/fabric-networking-blockentity-v0, fabric/fabric-networking-v0, fabric/fabric-object-builder-api-v1, fabric/fabric-object-builders-v0, fabric/fabric-registry-sync-v0, fabric/fabric-renderer-api-v1, fabric/fabric-renderer-indigo, fabric/fabric-renderer-registries-v1, fabric/fabric-rendering-data-attachment-v1, fabric/fabric-rendering-fluids-v1, fabric/fabric-rendering-v0, fabric/fabric-rendering-v1, fabric/fabric-resource-loader-v0, fabric/fabric-screen-handler-api-v1, fabric/fabric-tag-extensions-v0, fabric/fabric-textures-v0, fabric/fabric-tool-attribute-api-v1, fabric/fabricloader, file/Hussar Pack, file/Clear Glass.zip, file/Oar-less Boats.zip, file/Sounds of the Hussars, file/§r§r, fabric/capes, fabric/okzoomer, fabric/sodium, fabric/lambdynlights, fabric/lithium, fabric/modmenu, fabric/phosphor, fabric/spruceui
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor

**Comment by Setadokalo** [comment]
this should be fixed by the next release (currently processing on curseforge)
