### ISSUE TITLE
Crash with optifine/optifabric 1.16.4

### ISSUE THREAD

**Issue by helpimnotdrowning** [Setadokalo/custom-fog#6]
Getting a crash with this mod and optifabric, other crash reports on google with the same error (NoSuchMethodError: net.minecraft.class_758.setupFog(...)) have optifabric in them.

The game starts up to the title screen (using NotEnoughCrashes) and goes into amy menu, but trying to join a world will crash the game.

[crash-2020-11-12_15.34.15-client.txt](https://github.com/Setadokalo/custom-fog/files/5533440/crash-2020-11-12_15.34.15-client.txt)

OS: Windows 10 2004
JRE: AdoptOpenJDK 1.8.0_272
RAM: 5GB allocated

**Comment by Setadokalo** [comment]
Knowing Optifine it's probably messing up the method signature or something evil like that. And for the reasons listed in [this gist](https://gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754), I don't plan on supporting Optifabric. Optifine includes a limited version of this with its fog distance setting.
