### ISSUE TITLE
Can't disable custom fog, even with mod uninstalled (1.16.4) (Custom Fog 1.2.0)

### ISSUE THREAD

**Issue by Jarfeh** [Setadokalo/custom-fog#7]
After installing the mod, I found that the nether has the overworld's fog, so I tried uninstalling. The fog has not returned to its original color, even though I don't have the mod installed anymore.

**Comment by Setadokalo** [comment]
There's two problems here, so I'll address them seperately:
"the nether has the overworld's fog": yeah, by default the custom fog will apply to the overworld and the nether, but not the end. If you want to disable the mod in the nether, you can edit the config and change the line that reads 
```
dimensionsList = ["minecraft:the_end"]
```
to be 
```
dimensionsList = ["minecraft:the_end", "minecraft:the_nether"]
```
---
As to the second problem, "tried uninstalling... the fog has not returned to it's original color" - Custom Fog shouldn't change the color of the fog, ever; it just changes it's intensity. Assuming you mean it's density, I tried this out myself, and the fog goes back to it's vanilla appearance as soon as the mod is uninstalled. Are you sure it's not a different mod?

**Comment by Jarfeh** [comment]
You were right. The problem was related to colormatic. Thank you for your help on the blacklist format, I couldn't figure out how to format it properly.
